apiVersion: v1
kind: Pod
metadata:
  name: kubia-hostport 
spec:
  containers:
    - image: luksa/kubia
      name: kubia
      ports:
      - containerPort: 8080 # The container can be reached on port 8080 of the pod’s IP.
        hostPort: 9000 # It can also be reached on port 9000 of the node it’s deployed on.
        protocol: TCP