apiVersion: v1
kind: Pod
metadata:
  name: pod-run-as-non-root 
spec:
  containers: 
  - name: main
    image: alpine
    command: ["/bin/sleep", "999999"]
    securityContext:
      runAsNonRoot: true # This container will only be allowed to run as a non-root user.