apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc #name of the claim
spec:
  resources:
    requests:
      storage: 1Gi # size
  accessModes:
  - ReadWriteOnce # supports a single client
  storageClassName: ""